SPAWN:
  ENABLED: true
  JOIN: true
  LOCATION:
    WORLD: "world"
    X: 0.5
    Y: 64
    Z: 0.5
    YAW: 180
    PITCH: 180

DOUBLE_JUMP_CONFIG:
  ENABLED: true
  HEIGHT_VALUE: 1.0
  LENGTH-MULTIPLIER: 1.5
  SHIFT-BOST-ENABLED: true
  SHIFT-MULTIPLIER: 3.0

JOIN_MESSAGE:
  ENABLED:
    MESSAGE: "&7[&a+&7] &a%player% &7haas joined the server!"