SPAWN:
  ENABLED: true
  JOIN: true
  LOCATION:
    WORLD: "world"
    X: 0.5
    Y: 64
    Z: 0.5
    YAW: 180
    PITCH: 180

DOUBLE_JUMP_CONFIG:
  ENABLED: true
  HEIGHT_VALUE: 1.0
  LENGTH-MULTIPLIER: 1.5
  SHIFT-BOST-ENABLED: true
  SHIFT-MULTIPLIER: 3.0

JOIN:
  CLEAR-CHAT: true
  MESSAGE:
    ENABLED: true
    CONTENT: "&7[&a+&7] &a%player% &7haas joined the server!"
  MOTD:
    ENABLED: true
    LINES:
      - "------------------------------------------"
      - " "
      - "&bWelcome &f%username%, &fto &bLunar Network"
      - " "
      - "&7* &fWebsite: &bwww.lunar.gg"
      - "&7* &fStore: &bstore.lunar.gg"
      - "&7* &fDiscord: &bdiscord.lunar.gg"
      - " "
      - "------------------------------------------"