double-jump-config:
  enabled: true
  height-value: 1.0
  length-multiplier: 1.5
  shift-boost-enabled: true
  shift-multiplier: 3.0

JOIN_MESSAGE:
  ENABLED:
    MESSAGE: "&7[&a+&7] &a%player% &7haas joined the server!"