SPAWN:
  ENABLED: true
  JOIN: true
  LOCATION:
    WORLD: "world"
    X: 0
    Y: 100
    Z: 0
    YAW: 0
    PITCH: 0

BLOCKED-COMMANDS:
  ENABLED: true
  NO-PERMISSION: "&cYou don't have permission to do this command!"
  LIST:
    - pl
    - plugins
    - ver
    - version
    - about
    - icanhasbukkit
    - bukkit:?

DOUBLE_JUMP_CONFIG:
  ENABLED: true
  HEIGHT_VALUE: 1.0
  LENGTH-MULTIPLIER: 1.5
  SHIFT-BOST-ENABLED: true
  SHIFT-MULTIPLIER: 3.0

WORLD:
  SETTINGS:
    MOBS: false
    WEATHER: false

PLAYER:
  SPEED:
    ENABLED: true
    VALUE: 4

JOIN:
CLEAR-CHAT: true
MESSAGE:
  ENABLED: true
  CONTENT: "&7[&a+&7] &a%player% &7haas joined the server!"
SOUND: "ENTITY_PLAYER_LEVELUP"
MOTD:
  ENABLED: true
  LINES:
      - "------------------------------------------"
      - " "
      - "&bWelcome &f%username%, &fto &bLunar Network"
      - " "
      - "&7* &fWebsite: &bwww.lunar.gg"
      - "&7* &fStore: &bstore.lunar.gg"
      - "&7* &fDiscord: &bdiscord.lunar.gg"
      - " "
      - "------------------------------------------"